FROM node:16-alpine

RUN apk add  --no-cache git nano ffmpeg 

RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot
COPY . /usr/src/bot

RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot

COPY package.json /usr/src/bot
RUN npm install
COPY . /usr/src/bot
CMD ["node", "index.js"]